apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-agent-patcher
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app.name }}-agent-patcher
subjects:
- kind: ServiceAccount
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
